[package]
name = "snippeter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0"
dotenv = "0.15"
serde = {version = "1.0", features = ["derive"]}
bincode = "1.3"
fuse-rust = "0.3.1"